apiVersion: v1
kind: Service
metadata:
  name: chucknorris-app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: chucknorris-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
