apiVersion: v1
kind: Service
metadata:
  name: chucknorris-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: NodePort
  selector:
    app: chucknorris-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
